# Generated by Django 5.0.1 on 2024-02-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("idade", models.PositiveIntegerField()),
                ("endereco", models.CharField(max_length=255)),
                ("cep", models.CharField(max_length=10)),
                ("pais", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProfissionalSaude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especialidade", models.CharField(max_length=100)),
                ("registro", models.CharField(max_length=20, unique=True)),
                (
                    "clientes",
                    models.ManyToManyField(
                        related_name="profissionais_saude_associados",
                        to="base.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="profissionais_saude",
            field=models.ManyToManyField(
                related_name="clientes_associados", to="base.profissionalsaude"
            ),
        ),
    ]
