# Generated by Django 5.0.1 on 2024-03-13 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(db_column="senha", max_length=128)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("idade", models.PositiveIntegerField(null=True)),
                ("endereco", models.CharField(max_length=255, null=True)),
                ("cep", models.CharField(max_length=10, null=True)),
                ("pais", models.CharField(max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(null=True)),
                ("hora", models.TimeField(null=True)),
                ("local", models.CharField(max_length=500, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfissionalSaude",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("especialidade", models.CharField(max_length=100)),
                ("registro", models.CharField(max_length=20, null=True, unique=True)),
                (
                    "clientes",
                    models.ManyToManyField(
                        related_name="profissionais_saude_associados",
                        to="base.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("data", models.DateField(null=True)),
                ("hora", models.TimeField(null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="base.chat",
                    ),
                ),
                (
                    "profissionais_saude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.profissionalsaude",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="profissionais_saude",
            field=models.ManyToManyField(
                related_name="clientes_associados", to="base.profissionalsaude"
            ),
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(null=True)),
                ("hora", models.TimeField(null=True)),
                ("local", models.CharField(max_length=255, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.customer"
                    ),
                ),
                (
                    "profissional_saude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.profissionalsaude",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chat",
            name="profissionais_saude",
            field=models.ManyToManyField(
                related_name="chats_associados", to="base.profissionalsaude"
            ),
        ),
    ]
